// This file just declares the types of the (nonstandard) globals made available by the JS runtime.
// This should be autogenerated by the build and some smart attributes on things in rust, eventually, rather than manually maintained.

declare namespace Deno {
    namespace core {
        function print(arg: string): void; // technically a deno internal, but you can't use deno_console in js without relying on it anyway, so may as well use it directly
    }
}
